version: "3.8"
services:
    mongodb:
        image: mongo
        container_name: mongodb
        restart: always
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root
            MONGO_USER: a
            MONGO_PASSWORD: a
            MONGO_DATABASE: items
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db
            - ./mongo/scripts:/docker-entrypoint-initdb.d/:ro

    app:
        build:
            context: .
            dockerfile: Dockerfile
        #     args:
        #         PROTOCOL: http
        #         HOST: 192.168.1.20
        #         PORT: 3000
        image: mongo-express

        restart: always
        depends_on:
            - mongodb
        environment:
            DATABASE_URI: mongodb://a:a@mongodb:27017/items
            # PROTOCOL: http
            # HOST: 192.168.1.20
            # PORT: 3000
        ports:
            - "3000:3000"

volumes:
    mongodb_data:
        driver: local
